import React, { useEffect, useState } from 'react';
import { StyleSheet, Text, View, Button, Alert, ScrollView } from 'react-native';
import messaging, { RemoteMessage } from "@react-native-firebase/messaging";
import { StatusBar } from 'expo-status-bar';
import * as Notifications from "expo-notifications";

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: true,
    shouldSetBadge: true,
    shouldShowBanner: false,
    shouldShowList: true,
  }),
});

// Move handler outside the component and ensure it handles all cases
async function handleRemoteMessage(remoteMessage: RemoteMessage) {
  console.log("Remote Message received:", JSON.stringify(remoteMessage));

  const title = remoteMessage.notification?.title ?? "Default Title";
  const body = remoteMessage.notification?.body ?? "Default Body";

  if (
    remoteMessage.data?.type === "self-schedule" &&
    typeof remoteMessage.data?.time === "string"
  ) {
    console.log("how we did it !", remoteMessage.data);
    await Notifications.scheduleNotificationAsync({
      content: { title, body, data: remoteMessage.data },
      trigger: {
        date: new Date(remoteMessage.data?.time),
        type: Notifications.SchedulableTriggerInputTypes.DATE,
      },
    });
  } else {
    // Catch-all for other message types or plain notifications
    await Notifications.scheduleNotificationAsync({
      content: { title, body, data: remoteMessage.data },
      trigger: null,
    });
  }
}

// Register background handler outside the component
messaging().setBackgroundMessageHandler(handleRemoteMessage);

export default function App() {
  const [token, setToken] = useState<string>("");
  async function requestUserPermission() {
    try {
      const authStatus = await messaging().requestPermission();
      const enabled =
        authStatus === messaging.AuthorizationStatus.AUTHORIZED ||
        authStatus === messaging.AuthorizationStatus.PROVISIONAL;

      if (enabled) {
        console.log('Authorization status:', authStatus);
        getToken();
      } else {
        console.log('Permission not granted');
        Alert.alert('Permission Denied', 'Notifications permission is required for FCM.');
      }
    } catch (error) {
      console.error('Error requesting permission:', error);
    }
  }

  async function getToken() {
    try {
      const fcmToken = await messaging().getToken();
      if (fcmToken) {
        console.log('--- FCM TOKEN ---');
        console.log(fcmToken);
        console.log('-----------------');
        setToken(fcmToken);
      }
    } catch (error) {
      console.error('Error getting FCM token:', error);
    }
  }

  async function revokeToken() {
    try {
      await messaging().deleteToken();
      setToken("");
      Alert.alert('Success', 'Token revoked successfully. A new token can be generated by clicking Refresh.');
      console.log('Token revoked');
    } catch (error) {
      console.error('Error revoking token:', error);
      Alert.alert('Error', 'Failed to revoke token.');
    }
  }

  useEffect(() => {
    requestUserPermission();

    // Listen to foreground messages
    const unsubscribe = messaging().onMessage(handleRemoteMessage);

    // Handle token refresh
    const onTokenRefresh = messaging().onTokenRefresh(fcmToken => {
      console.log('Token refreshed:', fcmToken);
      setToken(fcmToken);
    });

    return () => {
      unsubscribe();
      onTokenRefresh();
    };
  }, []);

  return (
    <ScrollView contentContainerStyle={styles.container}>
      <View style={styles.header}>
        <Text style={styles.title}>Firebase FCM POC</Text>
        <Text style={styles.subtitle}>TypeScript & Bun Implementation</Text>
      </View>

      <View style={styles.card}>
        <Text style={styles.label}>Token Status:</Text>
        <Text style={[styles.status, { color: token ? '#34C759' : '#FF3B30' }]}>
          {token ? 'ACTIVE' : 'REVOKED / NONE'}
        </Text>
      </View>

      {token ? (
        <View style={styles.card}>
          <Text style={styles.label}>Current FCM Token:</Text>
          <View style={styles.tokenBox}>
            <Text selectable style={styles.tokenText}>{token}</Text>
          </View>
        </View>
      ) : null}

      <View style={styles.actions}>
        <View style={styles.buttonWrapper}>
          <Button 
            title="Revoke Token" 
            onPress={revokeToken} 
            color="#FF3B30" 
            disabled={!token}
          />
        </View>
        <View style={styles.buttonWrapper}>
          <Button 
            title="Generate/Refresh Token" 
            onPress={getToken} 
            color="#007AFF"
          />
        </View>
      </View>

      <View style={styles.footer}>
        <Text style={styles.footerText}>
          Run with 'bun expo run:android' or 'bun expo run:ios'
        </Text>
      </View>
      
      <StatusBar style="auto" />
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: '#F2F2F7',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  header: {
    alignItems: 'center',
    marginBottom: 30,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#1C1C1E',
  },
  subtitle: {
    fontSize: 16,
    color: '#8E8E93',
    marginTop: 5,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    width: '100%',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: '#8E8E93',
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  status: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  tokenBox: {
    backgroundColor: '#F2F2F7',
    padding: 12,
    borderRadius: 8,
    marginTop: 4,
  },
  tokenText: {
    fontSize: 12,
    fontFamily: 'monospace',
    color: '#1C1C1E',
  },
  actions: {
    width: '100%',
    marginTop: 10,
  },
  buttonWrapper: {
    marginVertical: 8,
    borderRadius: 10,
    overflow: 'hidden',
  },
  footer: {
    marginTop: 40,
  },
  footerText: {
    fontSize: 12,
    color: '#8E8E93',
    textAlign: 'center',
  },
});
